import type { FormDefinition, WorkflowDefinition } from "@erp/workflow";
import { withFormId } from "@erp/workflow";

/** Catalog seed forms — layout[{ widget, props }] only (no showItems / component / formKey). */
export const SO_STANDARD_FORMS: FormDefinition[] = [
  withFormId({
    key: "sales_review_form",
    id: "sales-review",
    title: "Sales review",
    description: "Add or remove products, confirm qty.",
    themeId: "oms-default",
    confirmLabel: "Complete this step →",
    layout: [
      { widget: "FormFields", props: {} },
      { widget: "ProductList", props: { editable: true, showPrice: true, allowAdd: true, allowRemove: true } },
      { widget: "CatalogSearch", props: {} },
      { widget: "ActionButtons", props: {} },
    ],
    fields: [
      { key: "remarks", label: "Remarks", type: "text", scope: "order" },
      { key: "deliveryDate", label: "Delivery date", type: "text", scope: "order" },
    ],
  }),
  withFormId({
    key: "inventory_form",
    id: "inventory",
    title: "Verify inventory",
    description: "Enter available qty. Shortage unlocks procurement.",
    themeId: "oms-default",
    layout: [
      { widget: "FormFields", props: {} },
      { widget: "ActionButtons", props: {} },
    ],
    fields: [
      {
        key: "availableQty",
        label: "Available qty",
        type: "number",
        scope: "per-item",
        source: "quantity",
        required: true,
      },
    ],
  }),
  withFormId({
    key: "procurement_form",
    id: "procurement",
    title: "Procurement",
    theme: "amber",
    themeId: "oms-attention",
    description: "Raise vendor request for missing quantity.",
    confirmLabel: "Send to vendor →",
    layout: [
      { widget: "ProductList", props: { editable: false } },
      { widget: "ActionButtons", props: { label: "Send to vendor →" } },
    ],
  }),
  withFormId({
    key: "pricing_form",
    id: "pricing",
    title: "Pricing",
    themeId: "oms-default",
    layout: [
      { widget: "FormFields", props: {} },
      { widget: "ActionButtons", props: {} },
    ],
    fields: [
      { key: "purchasePrice", label: "Purchase price", type: "number", scope: "per-item", required: true },
      {
        key: "unitPrice",
        label: "Sell price",
        type: "readonly",
        scope: "per-item",
        source: "unitPrice",
      },
    ],
  }),
  withFormId({
    key: "warehouse_form",
    id: "warehouse",
    title: "Warehouse pick & pack",
    description: "Confirm items are picked and packed.",
    themeId: "oms-default",
    layout: [
      { widget: "ProductList", props: { editable: false } },
      { widget: "ActionButtons", props: {} },
    ],
  }),
  withFormId({
    key: "dispatch_form",
    id: "dispatch",
    title: "Dispatch",
    themeId: "oms-default",
    layout: [
      { widget: "FormFields", props: {} },
      { widget: "ActionButtons", props: {} },
    ],
    fields: [
      { key: "vehicleInfo", label: "Vehicle no.", type: "text", scope: "order", required: true },
      {
        key: "assignedDriverId",
        label: "Driver name / ID",
        type: "text",
        scope: "order",
        required: true,
      },
    ],
  }),
  withFormId({
    key: "delivery_form",
    id: "delivery",
    title: "Delivery confirmation",
    description: "Confirm delivery to customer.",
    themeId: "oms-default",
    layout: [
      { widget: "ProductList", props: { editable: false } },
      { widget: "ActionButtons", props: {} },
    ],
  }),
  withFormId({
    key: "invoice_form",
    id: "invoice",
    title: "Invoice",
    themeId: "oms-default",
    layout: [
      { widget: "ProductList", props: { editable: false, showPrice: true } },
      { widget: "ActionButtons", props: {} },
    ],
  }),
  withFormId({
    key: "payment_form",
    id: "payment",
    title: "Collect payment",
    themeId: "oms-default",
    layout: [
      { widget: "ProductList", props: { editable: false, showPrice: true } },
      { widget: "ActionButtons", props: {} },
    ],
  }),
];

function formRef(formId: string, version = 1) {
  return { type: "FORM" as const, id: formId, version };
}

/** Built-in sequential SO_STANDARD v5 — published via designer/API; engine loads JSON only. */
export const SO_STANDARD_V5: WorkflowDefinition = {
  template: "SO_STANDARD",
  version: 6,
  name: "Sales Order Standard",
  description:
    "Sequential: Sales → Inventory → Procurement? → Pricing → Warehouse → Dispatch → Delivery → Invoice → Payment → Close",
  entityTypes: ["SALES_ORDER"],
  variableDefaults: { shortage: false },
  forms: SO_STANDARD_FORMS,
  activities: [
    {
      key: "sales_review",
      type: "SALES_REVIEW",
      kind: "HUMAN",
      label: "Sales review",
      assetRef: formRef("sales-review"),
      roleHint: "SALES_EXECUTIVE",
      permissions: { claim: ["SALES_EXECUTIVE"], complete: ["SALES_EXECUTIVE"] },
      projectionStatus: "CONFIRMED",
    },
    {
      key: "inventory",
      type: "INVENTORY_CHECK",
      kind: "HUMAN",
      label: "Inventory check",
      assetRef: formRef("inventory"),
      roleHint: "SALES_EXECUTIVE",
      permissions: { claim: ["SALES_EXECUTIVE"], complete: ["SALES_EXECUTIVE"] },
      projectionStatus: "FULFILLING",
    },
    {
      key: "procurement",
      type: "PROCUREMENT_REQUEST",
      kind: "HUMAN",
      label: "Procurement",
      optional: true,
      condition: "shortage",
      assetRef: formRef("procurement"),
      roleHint: "SALES_EXECUTIVE",
      permissions: { claim: ["SALES_EXECUTIVE"], complete: ["SALES_EXECUTIVE"] },
    },
    {
      key: "pricing",
      type: "PRICING_REVIEW",
      kind: "HUMAN",
      label: "Pricing review",
      assetRef: formRef("pricing"),
      roleHint: "PRICING_EXECUTIVE",
      permissions: {
        claim: ["PRICING_EXECUTIVE"],
        complete: ["PRICING_EXECUTIVE"],
        reassign: ["PRICING_MANAGER", "ADMIN"],
      },
      projectionStatus: "FULFILLING",
    },
    {
      key: "warehouse",
      type: "WAREHOUSE_PICK",
      kind: "HUMAN",
      label: "Warehouse pick",
      assetRef: formRef("warehouse"),
      roleHint: "DISPATCH_EXECUTIVE",
      permissions: { claim: ["DISPATCH_EXECUTIVE"], complete: ["DISPATCH_EXECUTIVE"] },
      projectionStatus: "READY_FOR_DISPATCH",
    },
    {
      key: "dispatch",
      type: "DISPATCH",
      kind: "HUMAN",
      label: "Dispatch",
      assetRef: formRef("dispatch"),
      roleHint: "DISPATCH_EXECUTIVE",
      permissions: { claim: ["DISPATCH_EXECUTIVE"], complete: ["DISPATCH_EXECUTIVE"] },
      projectionStatus: "DISPATCHED",
    },
    {
      key: "deliver",
      type: "DELIVERY_CONFIRM",
      kind: "HUMAN",
      label: "Delivery confirmation",
      assetRef: formRef("delivery"),
      roleHint: "DELIVERY_EXECUTIVE",
      permissions: { claim: ["DELIVERY_EXECUTIVE"], complete: ["DELIVERY_EXECUTIVE"] },
      projectionStatus: "DELIVERED",
    },
    {
      key: "invoice",
      type: "INVOICE_GENERATE",
      kind: "HUMAN",
      label: "Invoice",
      assetRef: formRef("invoice"),
      roleHint: "ACCOUNTANT",
      permissions: { claim: ["ACCOUNTANT"], complete: ["ACCOUNTANT"] },
      retryPolicy: { maxAttempts: 3, backoffMs: 2000, backoffMultiplier: 2, timeoutMs: 600_000 },
      projectionStatus: "INVOICED",
    },
    {
      key: "payment",
      type: "PAYMENT_COLLECTION",
      kind: "HUMAN",
      label: "Collect payment",
      assetRef: formRef("payment"),
      roleHint: "ACCOUNTANT",
      permissions: { claim: ["ACCOUNTANT"], complete: ["ACCOUNTANT"] },
      projectionStatus: "PAID",
    },
    {
      key: "close",
      type: "ORDER_CLOSE",
      kind: "SYSTEM",
      label: "Close order",
      autoComplete: true,
      projectionStatus: "CLOSED",
    },
  ],
  edges: [
    { from: "sales_review", to: "inventory" },
    { from: "inventory", to: "procurement" },
    { from: "inventory", to: "pricing" },
    { from: "procurement", to: "pricing" },
    { from: "pricing", to: "warehouse" },
    { from: "warehouse", to: "dispatch" },
    { from: "dispatch", to: "deliver" },
    { from: "deliver", to: "invoice" },
    { from: "invoice", to: "payment" },
    { from: "payment", to: "close" },
  ],
  layout: {
    sales_review: { x: 0, y: 0 },
    inventory: { x: 0, y: 100 },
    procurement: { x: 200, y: 200 },
    pricing: { x: 0, y: 300 },
    warehouse: { x: 0, y: 400 },
    dispatch: { x: 0, y: 500 },
    deliver: { x: 0, y: 600 },
    invoice: { x: 0, y: 700 },
    payment: { x: 0, y: 800 },
    close: { x: 0, y: 900 },
  },
};

export const SO_TASK_TYPES: { type: string; label: string; kind: "HUMAN" | "SYSTEM" }[] = [
  { type: "SALES_REVIEW", label: "Sales review", kind: "HUMAN" },
  { type: "INVENTORY_CHECK", label: "Inventory check", kind: "HUMAN" },
  { type: "PROCUREMENT_REQUEST", label: "Procurement request", kind: "HUMAN" },
  { type: "PRICING_REVIEW", label: "Pricing review", kind: "HUMAN" },
  { type: "WAREHOUSE_PICK", label: "Warehouse pick", kind: "HUMAN" },
  { type: "DISPATCH", label: "Dispatch", kind: "HUMAN" },
  { type: "DELIVERY_CONFIRM", label: "Delivery confirmation", kind: "HUMAN" },
  { type: "INVOICE_GENERATE", label: "Invoice generate", kind: "HUMAN" },
  { type: "PAYMENT_COLLECTION", label: "Payment collection", kind: "HUMAN" },
  { type: "ORDER_CLOSE", label: "Order close", kind: "SYSTEM" },
];
